### ISSUE TITLE
IDs should be a little more unique in custom modules to avoid potential clashes with contributed

### ISSUE THREAD

**Issue by ImThatTolu** [adigunsherif/Subscribe#10]
https://github.com/adigunsherif/Subscribe/blob/7404e26a37fd6bc8c9e3949e7696a259f4543871/src/Form/SubscribeForm.php#L17

**Comment by adigunsherif** [comment]
Right. The reason I used the convention of starting ID with module name but I should have used something like subscribe_subscribe_form

**Comment by ImThatTolu** [comment]
that works too
