### ISSUE TITLE
Copy & paste leftover?

### ISSUE THREAD

**Issue by ImThatTolu** [adigunsherif/Subscribe#4]
https://github.com/adigunsherif/Subscribe/blob/7404e26a37fd6bc8c9e3949e7696a259f4543871/subscribe.module#L58

**Comment by adigunsherif** [comment]
No. I had no time to get the body of the published content . So I wrote that in order that the email can be sent with this dummy body content.

**Comment by ImThatTolu** [comment]
Ok
