### ISSUE TITLE
Verbose:  $reply = NULL, $send = TRUE

### ISSUE THREAD

**Issue by ImThatTolu** [adigunsherif/Subscribe#5]
https://github.com/adigunsherif/Subscribe/blob/7404e26a37fd6bc8c9e3949e7696a259f4543871/subscribe.module#L61

**Comment by adigunsherif** [comment]
Can you please help me understand this? I don't

**Comment by ImThatTolu** [comment]
Verbose means you are writing more code than necessary

 $mailManager->mail('subscribe', 'subscribe', $email, $langcode, $params, $reply = NULL, $send = TRUE); ===  $mailManager->mail('subscribe', 'subscribe', $email, $langcode, $params);

**Comment by adigunsherif** [comment]
Oh. Now I understand. Thank you.
