### ISSUE TITLE
Always good practice to check for $key

### ISSUE THREAD

**Issue by ImThatTolu** [adigunsherif/Subscribe#7]
https://github.com/adigunsherif/Subscribe/blob/7404e26a37fd6bc8c9e3949e7696a259f4543871/subscribe.module#L92

**Comment by adigunsherif** [comment]
Okay. 
Ordinarily,  I was thinking I wouldn't have done this in code. I would rather pass this on to rules by firing a rules component/custom event.  This will give room for more flexibility without having to write code for sending mail.

**Comment by adigunsherif** [comment]
The main reason I didn't check for $key. Plus time constraints

**Comment by ImThatTolu** [comment]
This implementation is better than rules, As rules is a whole new dependency we have to account for just to send one email.
